In [8]:
import pandas as pd
import mysql.connector as conn

In [2]:
mydb = conn.connect(host = "Localhost" , user ="root" , passwd = "India123")

In [3]:
cursor = mydb.cursor()
cursor.execute("Show Databases")
cursor.fetchall()

[('bank',),
 ('database2',),
 ('databasetesthai',),
 ('information_schema',),
 ('mysql',),
 ('performance_schema',),
 ('sakila',),
 ('sys',),
 ('world',)]

In [4]:
cursor.execute("Create database Dressdb")

In [5]:
df1 = pd.read_excel("E:\DATA SCIENCE\data fsds_\Dress Sales.xlsx")
df1

,Dress_ID,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,D14,D15,D16,D17,D18,D19,D20,D21,D22,D23
0,1006032852,2114,2274,2491,2660,2727,2887,2930,3119,3204,...,3554,3624.0,3706,3746.0,3795.0,3832.0,3897,3923.0,3985.0,4048
1,1212192089,151,275,570,750,813,1066,1164,1558,1756,...,2710,2942.0,3258,3354.0,3475.0,3654.0,3911,4024.0,4125.0,4277
2,1190380701,6,7,7,7,8,8,9,10,10,...,11,11.0,11,11.0,11.0,11.0,11,11.0,11.0,11
3,966005983,1005,1128,1326,1455,1507,1621,1637,1723,1746,...,1878,1892.0,1914,1924.0,1929.0,1941.0,1952,1955.0,1959.0,1963
4,876339541,996,1175,1304,1396,1432,1559,1570,1638,1655,...,2032,2156.0,2252,2312.0,2387.0,2459.0,2544,2614.0,2693.0,2736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,0,0,0,560,554,544,537,525,519,...,400,388.0,360,364.0,372.0,377.0,380,382.0,384.0,285
496,722565148,0,0,0,875,866,861,854,850,844,...,859,866.0,882,888.0,895.0,898.0,906,913.0,919.0,931
497,532874347,0,0,0,734,728,726,715,694,690,...,616,597.0,586,569.0,561.0,555.0,551,546.0,535.0,520
498,655464934,0,0,0,254,259,261,263,268,270,...,257,256.0,255,254.0,253.0,250.0,249,249.0,249.0,248
499,919930954,0,0,0,538,545,558,563,578,585,...,628,632.0,639,645.0,651.0,655.0,660,668.0,674.0,680

In [6]:
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:India123@Localhost/Dressdb")

In [7]:
df1.to_sql("dresssalestab" ,index=None, con = engine)

500

In [8]:
df2=pd.read_excel("E:\DATA SCIENCE\data fsds_\Attribute DataSet.xlsx")
df2

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [9]:
df2.to_sql("attributetab" ,index = None , con=engine)

500

In [10]:
cursor.execute("use dressdb")

In [11]:
df3 = cursor.execute("select dresssalestab.Dress_ID from dresssalestab left join attributetab on dresssalestab.Dress_ID = attributetab.Dress_ID")

In [12]:
cursor.fetchall()

[(1006032852,),
 (1212192089,),
 (1190380701,),
 (966005983,),
 (876339541,),
 (1068332458,),
 (1220707172,),
 (1219677488,),
 (1219677488,),
 (1113094204,),
 (985292672,),
 (1117293701,),
 (898481530,),
 (957723897,),
 (749031896,),
 (1055411544,),
 (1162628131,),
 (624314841,),
 (830467746,),
 (840857118,),
 (1113221101,),
 (861754372,),
 (856178100,),
 (1122989777,),
 (840516484,),
 (768517084,),
 (1139843344,),
 (1004212992,),
 (1235426503,),
 (942808364,),
 (629131530,),
 (851945460,),
 (1150275464,),
 (1026634314,),
 (978773911,),
 (827791337,),
 (640823350,),
 (801861988,),
 (1060207186,),
 (1054679816,),
 (941190190,),
 (943844640,),
 (661795386,),
 (875312593,),
 (971387676,),
 (1021185637,),
 (1163826114,),
 (735635595,),
 (1175184188,),
 (679415939,),
 (884147971,),
 (841203385,),
 (841203385,),
 (1117997056,),
 (1160536550,),
 (828623528,),
 (763708514,),
 (1153442065,),
 (743729613,),
 (1000493051,),
 (911085061,),
 (1174854264,),
 (1053296757,),
 (1033843327,),
 (1083779666,),
 (1083779666,),
 (746255172,),
 (1100974555,),
 (1019134411,),
 (1072477320,),
 (638423913,),
 (936425780,),
 (1146088956,),
 (864253055,),
 (1210582154,),
 (926480831,),
 (757260823,),
 (630561922,),
 (734061929,),
 (842060995,),
 (1078431253,),
 (939770391,),
 (943188872,),
 (1130994272,),
 (907117649,),
 (967999477,),
 (944656411,),
 (1096779299,),
 (1036333255,),
 (1065316076,),
 (995802744,),
 (1018110870,),
 (850586379,),
 (1169895668,),
 (688966772,),
 (1194626925,),
 (876708804,),
 (876708804,),
 (1118628066,),
 (1027818824,),
 (891103323,),
 (1166855026,),
 (1023850025,),
 (805438829,),
 (836788720,),
 (835787654,),
 (1148457078,),
 (887476609,),
 (535968075,),
 (892801580,),
 (732650169,),
 (680070369,),
 (1002440915,),
 (737538048,),
 (1104450248,),
 (797673346,),
 (1039982741,),
 (829087315,),
 (1032990258,),
 (1032990258,),
 (939422280,),
 (974746803,),
 (1018130478,),
 (956758119,),
 (903426442,),
 (861626197,),
 (1077015977,),
 (817870237,),
 (1078996836,),
 (881530990,),
 (937046375,),
 (870994067,),
 (870994067,),
 (893330898,),
 (822053936,),
 (1059959935,),
 (1197204708,),
 (713439584,),
 (732736124,),
 (709353440,),
 (709353440,),
 (1031230798,),
 (1031230798,),
 (1225512606,),
 (1158347154,),
 (976975672,),
 (976975672,),
 (520233308,),
 (935827969,),
 (1130624045,),
 (547555172,),
 (1083323104,),
 (955188745,),
 (1140306858,),
 (895807023,),
 (818505402,),
 (897981100,),
 (973481686,),
 (1021375534,),
 (549437715,),
 (1097548715,),
 (578702321,),
 (1155548915,),
 (1199064757,),
 (1078994436,),
 (949226757,),
 (832191944,),
 (869572905,),
 (896048351,),
 (896048351,),
 (854444464,),
 (1246749980,),
 (849613634,),
 (1019768234,),
 (785830491,),
 (832391864,),
 (1069595866,),
 (733715437,),
 (733715437,),
 (828949946,),
 (765264430,),
 (722020708,),
 (980295760,),
 (913978120,),
 (1062354779,),
 (1062354779,),
 (1051749304,),
 (1206128856,),
 (956453735,),
 (767971724,),
 (722565148,),
 (722565148,),
 (1167448608,),
 (549159213,),
 (549159213,),
 (940918554,),
 (522776523,),
 (658650071,),
 (560474456,),
 (560474456,),
 (1150052066,),
 (929797706,),
 (886351969,),
 (1071947910,),
 (813753347,),
 (733134203,),
 (733134203,),
 (851256794,),
 (751049573,),
 (882490248,),
 (541172235,),
 (727676110,),
 (727676110,),
 (891631697,),
 (1059306768,),
 (764321904,),
 (902108125,),
 (874397327,),
 (861698160,),
 (981437831,),
 (1036456647,),
 (951280194,),
 (1079373429,),
 (1079373429,),
 (747381880,),
 (1099363892,),
 (941333009,),
 (819651586,),
 (1043590098,),
 (1091666465,),
 (863336720,),
 (863336720,),
 (771972560,),
 (756492184,),
 (1097157656,),
 (1097157656,),
 (573923366,),
 (756620535,),
 (765350508,),
 (968294356,),
 (1017678811,),
 (933231033,),
 (933231033,),
 (1199765487,),
 (965817793,),
 (1074432879,),
 (1132858821,),
 (905732124,),
 (905732124,),
 (711045472,),
 (923983419,),
 (733025646,),
 (733025646,),
 (720099861,),
 (923915314,),
 (1077555214,),
 (1216538883,),
 (531254082,),
 (890279029,),
 (995964089,),
 (868453353,),
 (1024954013,),
 (685606338,),
 (877962269,),
 (995644296,),
 (1066273951,),
 (822176645,),
 (659466129,),
 (694493217,),
 (793162246,),
 (793162246,),
 (817945281,),
 (920902282,),
 (727820291,),
 (699738864,),
 (699738864,),
 (1197211965,),
 (682561447,),
 (999081623,),
 (1108613896,),
 (1054555186,),
 (915238287,),
 (1107279894,),
 (1163040038,),
 (1091877430,),
 (1053467336,),
 (609889168,),
 (662727740,),
 (1090993173,),
 (963684109,),
 (619817668,),
 (1066740059,),
 (732184480,),
 (1044683061,),
 (579010251,),
 (751364623,),
 (898316819,),
 (622667306,),
 (809344968,),
 (754138176,),
 (674192921,),
 (726446177,),
 (1193747589,),
 (676827184,),
 (619996560,),
 (618420156,),
 (689486739,),
 (751364614,),
 (825341937,),
 (736813752,),
 (636178374,),
 (743485617,),
 (933951149,),
 (684561284,),
 (616295248,),
 (736076633,),
 (1108073621,),
 (1053002876,),
 (444282011,),
 (949336768,),
 (961972778,),
 (893088817,),
 (952724683,),
 (855037000,),
 (660016574,),
 (738079582,),
 (861001391,),
 (1099696103,),
 (1044288976,),
 (890848361,),
 (929503394,),
 (1015249105,),
 (707537639,),
 (702984554,),
 (896048351,),
 (896048351,),
 (1023830972,),
 (959052557,),
 (1246945687,),
 (510519284,),
 (1079958917,),
 (1024325244,),
 (841203385,),
 (841203385,),
 (1104504876,),
 (1010356223,),
 (1031230798,),
 (1031230798,),
 (908989488,),
 (822081627,),
 (1116072373,),
 (856139963,),
 (1032982013,),
 (879756967,),
 (912614690,),
 (1072784739,),
 (945651303,),
 (858212832,),
 (1219677488,),
 (1219677488,),
 (886501087,),
 (944264938,),
 (918722829,),
 (750670078,),
 (1028061165,),
 (699738864,),
 (699738864,),
 (905732124,),
 (905732124,),
 (961230947,),
 (849947393,),
 (857432541,),
 (1088674674,),
 (939250541,),
 (876708804,),
 (876708804,),
 (1032990258,),
 (1032990258,),
 (880692544,),
 (958270190,),
 (732757918,),
 (898646576,),
 (950048509,),
 (754316257,),
 (598523814,),
 (774130360,),
 (555727400,),
 (537463111,),
 (933864550,),
 (944930838,),
 (901346821,),
 (818295153,),
 (733134203,),
 (733134203,),
 (943414146,),
 (709353440,),
 (709353440,),
 (1190383536,),
 (869138763,),
 (977173764,),
 (918331326,),
 (733715437,),
 (733715437,),
 (955679920,),
 (862814652,),
 (799301728,),
 (1039384371,),
 (746518490,),
 (720665176,),
 (1001750851,),
 (882975367,),
 (1069577979,),
 (1079373429,),
 (1079373429,),
 (711704151,),
 (876761815,),
 (1062354779,),
 (1062354779,),
 (727676110,),
 (727676110,),
 (845853510,),
 (832090686,),
 (839305476,),
 (855418066,),
 (1211480431,),
 (946741571,),
 (724177834,),
 (975877364,),
 (851697194,),
 (1108356000,),
 (871219565,),
 (1250787559,),
 (942245416,),
 (900108476,),
 (1019672746,),
 (783980024,),
 (970655043,),
 (1139064593,),
 (939389270,),
 (859321875,),
 (703395323,),
 (1083779666,),
 (1083779666,),
 (966030991,),
 (866405822,),
 (941564304,),
 (1119360745,),
 (932375745,),
 (789373177,),
 (1135456589,),
 (932913675,),
 (1217548862,),
 (755078866,),
 (1052420390,),
 (924108301,),
 (675980168,),
 (730603782,),
 (934830377,),
 (689406468,),
 (870994067,),
 (870994067,),
 (1016250560,),
 (860334943,),
 (863336720,),
 (863336720,),
 (835915937,),
 (944641715,),
 (869395176,),
 (1097435333,),
 (1124120907,),
 (1130463523,),
 (560474456,),
 (560474456,),
 (907669618,),
 (710089916,),
 (793162246,),
 (793162246,),
 (1065317917,),
 (737461130,),
 (663993130,),
 (933231033,),
 (933231033,),
 (743417270,),
 (798898277,),
 (549401113,),
 (857189807,),
 (1055149353,),
 (1199912555,),
 (1249825438,),
 (967191118,),
 (871620435,),
 (865490824,),
 (1079955163,),
 (600514129,),
 (976975672,),
 (976975672,),
 (720087997,),
 (699651184,),
 (605122868,),
 (1000425584,),
 (549159213,),
 (549159213,),
 (898316315,),
 (1017484769,),
 (733025646,),
 (733025646,),
 (909624960,),
 (1086459983,),
 (593007494,),
 (660179663,),
 (1097157656,),
 (1097157656,),
 (751776863,),
 (1253973206,),
 (828790972,),
 (933413410,),
 (550959163,),
 (933926000,),
 (953168456,),
 (1124754999,),
 (832949213,),
 (801216472,),
 (929898500,),
 (850490510,),
 (1099394392,),
 (674885710,),
 (1122991519,),
 (904781800,),
 (974438263,),
 (875608094,),
 (1061890181,),
 (1033144189,),
 (860406062,),
 (692445545,),
 (974775647,),
 (1109819647,),
 (1223469038,),
 (511503677,),
 (1190558632,),
 (641665398,),
 (964917582,),
 (859922576,),
 (817353671,),
 (990559192,),
 (713391965,),
 (722565148,),
 (722565148,),
 (532874347,),
 (655464934,),
 (919930954,)]

In [13]:
cursor.execute("select Style,count(*) from attributetab group by Style ")
cursor.fetchall()

[('Sexy', 76),
 ('Casual', 232),
 ('vintage', 25),
 ('Brief', 18),
 ('cute', 45),
 ('bohemian', 24),
 ('Novelty', 8),
 ('Flare', 2),
 ('party', 51),
 ('work', 17),
 ('OL', 1),
 ('fashion', 1)]

In [14]:
cursor.execute("select count(*) from attributetab where Recommendation=0")
cursor.fetchall()

[(290,)]

In [15]:
cursor.execute("select count(*) from attributetab where Recommendation=1")
cursor.fetchall()

[(210,)]

In [16]:
df1

,Dress_ID,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,D14,D15,D16,D17,D18,D19,D20,D21,D22,D23
0,1006032852,2114,2274,2491,2660,2727,2887,2930,3119,3204,...,3554,3624.0,3706,3746.0,3795.0,3832.0,3897,3923.0,3985.0,4048
1,1212192089,151,275,570,750,813,1066,1164,1558,1756,...,2710,2942.0,3258,3354.0,3475.0,3654.0,3911,4024.0,4125.0,4277
2,1190380701,6,7,7,7,8,8,9,10,10,...,11,11.0,11,11.0,11.0,11.0,11,11.0,11.0,11
3,966005983,1005,1128,1326,1455,1507,1621,1637,1723,1746,...,1878,1892.0,1914,1924.0,1929.0,1941.0,1952,1955.0,1959.0,1963
4,876339541,996,1175,1304,1396,1432,1559,1570,1638,1655,...,2032,2156.0,2252,2312.0,2387.0,2459.0,2544,2614.0,2693.0,2736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,0,0,0,560,554,544,537,525,519,...,400,388.0,360,364.0,372.0,377.0,380,382.0,384.0,285
496,722565148,0,0,0,875,866,861,854,850,844,...,859,866.0,882,888.0,895.0,898.0,906,913.0,919.0,931
497,532874347,0,0,0,734,728,726,715,694,690,...,616,597.0,586,569.0,561.0,555.0,551,546.0,535.0,520
498,655464934,0,0,0,254,259,261,263,268,270,...,257,256.0,255,254.0,253.0,250.0,249,249.0,249.0,248
499,919930954,0,0,0,538,545,558,563,578,585,...,628,632.0,639,645.0,651.0,655.0,660,668.0,674.0,680

In [21]:
cursor.execute("select  Dress_ID, coalesce(D1,0)+coalesce(D2,0)+coalesce(D3,0)+coalesce(D4,0)+coalesce(D5,0)+coalesce(D6,0)+coalesce(D7,0)+coalesce(D8,0)+coalesce(D9,0)+coalesce(D10,0)+coalesce(D11,0)+coalesce(D12,0)+coalesce(D13,0)+coalesce(D14,0)+coalesce(D15,0)+coalesce(D16,0)+coalesce(D17,0)+coalesce(D18,0)+coalesce(D19,0)+coalesce(D20,0)+coalesce(D21,0)+coalesce(D22,0)+coalesce(D23,0) as Total_Sale from dresssalestab")
cursor.fetchall()

[(1006032852, 75979.0),
 (1212192089, 52256.0),
 (1190380701, 223.0),
 (966005983, 39691.0),
 (876339541, 44077.0),
 (1068332458, 457.0),
 (1220707172, 7328.0),
 (1219677488, 3248.0),
 (1113094204, 494.0),
 (985292672, 300.0),
 (1117293701, 1911.0),
 (898481530, 2842.0),
 (957723897, 49983.0),
 (749031896, 75346.0),
 (1055411544, 1095.0),
 (1162628131, 2319.0),
 (624314841, 47998.0),
 (830467746, 401.0),
 (840857118, 299.0),
 (1113221101, 9998.0),
 (861754372, 6175.0),
 (856178100, 31467.0),
 (1122989777, 5216.0),
 (840516484, 42347.0),
 (768517084, 107.0),
 (1139843344, 518.0),
 (1004212992, 48440.0),
 (1235426503, 4696.0),
 (942808364, 11518.0),
 (629131530, 155927.0),
 (851945460, 26496.0),
 (1150275464, 5738.0),
 (1026634314, 18184.0),
 (978773911, 23200.0),
 (827791337, 41875.0),
 (640823350, 29528.0),
 (801861988, 32342.0),
 (1060207186, 1820.0),
 (1054679816, 12987.0),
 (941190190, 11693.0),
 (943844640, 2999.0),
 (661795386, 49173.0),
 (875312593, 11817.0),
 (971387676, 15506.0),
 (1021185637, 4451.0),
 (1163826114, 2133.0),
 (735635595, 91556.0),
 (1175184188, 635.0),
 (679415939, 20730.0),
 (884147971, 96.0),
 (841203385, 3943.0),
 (1117997056, 3947.0),
 (1160536550, 1341.0),
 (828623528, 27364.0),
 (763708514, 17079.0),
 (1153442065, 5905.0),
 (743729613, 10944.0),
 (1000493051, 9852.0),
 (911085061, 6751.0),
 (1174854264, 778.0),
 (1053296757, 105.0),
 (1033843327, 257.0),
 (1083779666, 1565.0),
 (746255172, 37083.0),
 (1100974555, 5614.0),
 (1019134411, 12001.0),
 (1072477320, 6722.0),
 (638423913, 601.0),
 (936425780, 7775.0),
 (1146088956, 182.0),
 (864253055, 1646.0),
 (1210582154, 11403.0),
 (926480831, 6835.0),
 (757260823, 957.0),
 (630561922, 15909.0),
 (734061929, 38251.0),
 (842060995, 594.0),
 (1078431253, 162.0),
 (939770391, 134.0),
 (943188872, 1871.0),
 (1130994272, 2455.0),
 (907117649, 24713.0),
 (967999477, 7218.0),
 (944656411, 7720.0),
 (1096779299, 582.0),
 (1036333255, 4018.0),
 (1065316076, 4464.0),
 (995802744, 6707.0),
 (1018110870, 8229.0),
 (850586379, 7522.0),
 (1169895668, 480.0),
 (688966772, 17272.0),
 (1194626925, 429.0),
 (876708804, 2996.0),
 (1118628066, 3744.0),
 (1027818824, 48.0),
 (891103323, 812.0),
 (1166855026, 69.0),
 (1023850025, 8696.0),
 (805438829, 13749.0),
 (836788720, 426.0),
 (835787654, 7831.0),
 (1148457078, 4030.0),
 (887476609, 11237.0),
 (535968075, 22147.0),
 (892801580, 6071.0),
 (732650169, 34651.0),
 (680070369, 9422.0),
 (1002440915, 1843.0),
 (737538048, 57543.0),
 (1104450248, 3358.0),
 (797673346, 17017.0),
 (1039982741, 604.0),
 (829087315, 7206.0),
 (1032990258, 2725.0),
 (939422280, 9070.0),
 (974746803, 3809.0),
 (1018130478, 6620.0),
 (956758119, 7868.0),
 (903426442, 16006.0),
 (861626197, 20839.0),
 (1077015977, 150.0),
 (817870237, 4536.0),
 (1078996836, 1748.0),
 (881530990, 11515.0),
 (937046375, 3439.0),
 (870994067, 3464.0),
 (893330898, 7852.0),
 (822053936, 3668.0),
 (1059959935, 76.0),
 (1197204708, 4385.0),
 (713439584, 9740.0),
 (732736124, 3615.0),
 (709353440, 5811.0),
 (1031230798, 2846.0),
 (1225512606, 270.0),
 (1158347154, 1460.0),
 (976975672, 2226.0),
 (520233308, 11041.0),
 (935827969, 1952.0),
 (1130624045, 1467.0),
 (547555172, 21772.0),
 (1083323104, 8830.0),
 (955188745, 5761.0),
 (1140306858, 2539.0),
 (895807023, 7351.0),
 (818505402, 1059.0),
 (897981100, 2086.0),
 (973481686, 9305.0),
 (1021375534, 7555.0),
 (549437715, 32300.0),
 (1097548715, 515.0),
 (578702321, 994.0),
 (1155548915, 151.0),
 (1199064757, 44.0),
 (1078994436, 195.0),
 (949226757, 3665.0),
 (832191944, 109.0),
 (869572905, 4765.0),
 (896048351, 3572.0),
 (854444464, 8291.0),
 (1246749980, 6915.0),
 (849613634, 424.0),
 (1019768234, 8822.0),
 (785830491, 434.0),
 (832391864, 1012.0),
 (1069595866, 80.0),
 (733715437, 6559.0),
 (828949946, 6160.0),
 (765264430, 11259.0),
 (722020708, 13804.0),
 (980295760, 5632.0),
 (913978120, 16361.0),
 (1062354779, 3857.0),
 (1051749304, 497.0),
 (1206128856, 6295.0),
 (956453735, 1906.0),
 (767971724, 1888.0),
 (722565148, 14748.0),
 (1167448608, 1208.0),
 (549159213, 4697.0),
 (940918554, 1870.0),
 (522776523, 9414.0),
 (658650071, 12607.0),
 (560474456, 6109.0),
 (1150052066, 4476.0),
 (929797706, 204.0),
 (886351969, 7793.0),
 (1071947910, 114.0),
 (813753347, 31663.0),
 (733134203, 3636.0),
 (851256794, 991.0),
 (751049573, 1974.0),
 (882490248, 6282.0),
 (541172235, 12217.0),
 (727676110, 2566.0),
 (891631697, 2125.0),
 (1059306768, 56.0),
 (764321904, 806.0),
 (902108125, 3302.0),
 (874397327, 4837.0),
 (861698160, 2183.0),
 (981437831, 1452.0),
 (1036456647, 704.0),
 (951280194, 8656.0),
 (1079373429, 1005.0),
 (747381880, 19026.0),
 (1099363892, 4352.0),
 (941333009, 3320.0),
 (819651586, 4225.0),
 (1043590098, 2423.0),
 (1091666465, 447.0),
 (863336720, 3006.0),
 (771972560, 7435.0),
 (756492184, 1195.0),
 (1097157656, 2761.0),
 (573923366, 6296.0),
 (756620535, 9670.0),
 (765350508, 8718.0),
 (968294356, 12854.0),
 (1017678811, 68.0),
 (933231033, 3790.0),
 (1199765487, 23.0),
 (965817793, 6445.0),
 (1074432879, 937.0),
 (1132858821, 57.0),
 (905732124, 2489.0),
 (711045472, 3560.0),
 (923983419, 721.0),
 (733025646, 13461.0),
 (720099861, 14733.0),
 (923915314, 6679.0),
 (1077555214, 2514.0),
 (1216538883, 9493.0),
 (531254082, 6087.0),
 (890279029, 3678.0),
 (995964089, 610.0),
 (868453353, 826.0),
 (1024954013, 5021.0),
 (685606338, 3830.0),
 (877962269, 1548.0),
 (995644296, 6245.0),
 (1066273951, 1551.0),
 (822176645, 4834.0),
 (659466129, 58.0),
 (694493217, 5602.0),
 (793162246, 24217.0),
 (817945281, 1981.0),
 (920902282, 3738.0),
 (727820291, 6003.0),
 (699738864, 4956.0),
 (1197211965, 195.0),
 (682561447, 1236.0),
 (999081623, 2451.0),
 (1108613896, 23.0),
 (1054555186, 98.0),
 (915238287, 2529.0),
 (1107279894, 56.0),
 (1163040038, 60.0),
 (1091877430, 30.0),
 (1053467336, 1282.0),
 (609889168, 2728.0),
 (662727740, 3892.0),
 (1090993173, 4412.0),
 (963684109, 1296.0),
 (619817668, 4140.0),
 (1066740059, 1311.0),
 (732184480, 1092.0),
 (1044683061, 613.0),
 (579010251, 1323.0),
 (751364623, 1645.0),
 (898316819, 1607.0),
 (622667306, 1619.0),
 (809344968, 6060.0),
 (754138176, 3193.0),
 (674192921, 3069.0),
 (726446177, 2082.0),
 (1193747589, 40.0),
 (676827184, 1891.0),
 (619996560, 3224.0),
 (618420156, 1928.0),
 (689486739, 511.0),
 (751364614, 2164.0),
 (825341937, 2088.0),
 (736813752, 804.0),
 (636178374, 1929.0),
 (743485617, 2102.0),
 (933951149, 1810.0),
 (684561284, 1406.0),
 (616295248, 2509.0),
 (736076633, 2056.0),
 (1108073621, 112.0),
 (1053002876, 541.0),
 (444282011, 1732.0),
 (949336768, 610.0),
 (961972778, 65.0),
 (893088817, 677.0),
 (952724683, 108.0),
 (855037000, 787.0),
 (660016574, 1287.0),
 (738079582, 2355.0),
 (861001391, 1344.0),
 (1099696103, 1506.0),
 (1044288976, 541.0),
 (890848361, 1710.0),
 (929503394, 4847.0),
 (1015249105, 5205.0),
 (707537639, 16225.0),
 (702984554, 1795.0),
 (896048351, 3170.0),
 (1023830972, 1113.0),
 (959052557, 4207.0),
 (1246945687, 1034.0),
 (510519284, 2888.0),
 (1079958917, 2715.0),
 (1024325244, 539.0),
 (841203385, 3251.0),
 (1104504876, 1000.0),
 (1010356223, 1070.0),
 (1031230798, 2514.0),
 (908989488, 45.0),
 (822081627, 11181.0),
 (1116072373, 1284.0),
 (856139963, 1261.0),
 (1032982013, 1452.0),
 (879756967, 11698.0),
 (912614690, 672.0),
 (1072784739, 2421.0),
 (945651303, 1371.0),
 (858212832, 9045.0),
 (1219677488, 1936.0),
 (886501087, 161.0),
 (944264938, 1644.0),
 (918722829, 1878.0),
 (750670078, 11359.0),
 (1028061165, 1305.0),
 (699738864, 4246.0),
 (905732124, 2244.0),
 (961230947, 1490.0),
 (849947393, 3792.0),
 (857432541, 1785.0),
 (1088674674, 1098.0),
 (939250541, 1866.0),
 (876708804, 2928.0),
 (1032990258, 2284.0),
 (880692544, 1299.0),
 (958270190, 893.0),
 (732757918, 15484.0),
 (898646576, 4069.0),
 (950048509, 932.0),
 (754316257, 3231.0),
 (598523814, 7730.0),
 (774130360, 42.0),
 (555727400, 8339.0),
 (537463111, 4533.0),
 (933864550, 2479.0),
 (944930838, 2854.0),
 (901346821, 1015.0),
 (818295153, 1458.0),
 (733134203, 3261.0),
 (943414146, 11741.0),
 (709353440, 5112.0),
 (1190383536, 2492.0),
 (869138763, 1055.0),
 (977173764, 1360.0),
 (918331326, 1785.0),
 (733715437, 5494.0),
 (955679920, 2125.0),
 (862814652, 2139.0),
 (799301728, 1444.0),
 (1039384371, 1628.0),
 (746518490, 4855.0),
 (720665176, 135.0),
 (1001750851, 410.0),
 (882975367, 3166.0),
 (1069577979, 1293.0),
 (1079373429, 966.0),
 (711704151, 9443.0),
 (876761815, 1310.0),
 (1062354779, 3441.0),
 (727676110, 2422.0),
 (845853510, 3570.0),
 (832090686, 5940.0),
 (839305476, 3017.0),
 (855418066, 2032.0),
 (1211480431, 2719.0),
 (946741571, 5910.0),
 (724177834, 9202.0),
 (975877364, 80.0),
 (851697194, 3463.0),
 (1108356000, 254.0),
 (871219565, 1559.0),
 (1250787559, 40.0),
 (942245416, 312.0),
 (900108476, 1381.0),
 (1019672746, 5572.0),
 (783980024, 4394.0),
 (970655043, 2066.0),
 (1139064593, 20.0),
 (939389270, 3023.0),
 (859321875, 2399.0),
 (703395323, 20.0),
 (1083779666, 1053.0),
 (966030991, 253.0),
 (866405822, 1163.0),
 (941564304, 2950.0),
 (1119360745, 99.0),
 (932375745, 3506.0),
 (789373177, 2495.0),
 (1135456589, 784.0),
 (932913675, 389.0),
 (1217548862, 843.0),
 (755078866, 1858.0),
 (1052420390, 502.0),
 (924108301, 1762.0),
 (675980168, 5100.0),
 (730603782, 4308.0),
 (934830377, 2534.0),
 (689406468, 878.0),
 (870994067, 2871.0),
 (1016250560, 5621.0),
 (860334943, 3254.0),
 (863336720, 2611.0),
 (835915937, 1529.0),
 (944641715, 1764.0),
 (869395176, 2373.0),
 (1097435333, 49.0),
 (1124120907, 1200.0),
 (1130463523, 871.0),
 (560474456, 5487.0),
 (907669618, 4.0),
 (710089916, 759.0),
 (793162246, 19996.0),
 (1065317917, 519.0),
 (737461130, 9287.0),
 (663993130, 1250.0),
 (933231033, 3199.0),
 (743417270, 2834.0),
 (798898277, 9090.0),
 (549401113, 4074.0),
 (857189807, 416.0),
 (1055149353, 680.0),
 (1199912555, 969.0),
 (1249825438, 1814.0),
 (967191118, 286.0),
 (871620435, 564.0),
 (865490824, 1171.0),
 (1079955163, 1828.0),
 (600514129, 1706.0),
 (976975672, 2953.0),
 (720087997, 8979.0),
 (699651184, 3042.0),
 (605122868, 4398.0),
 (1000425584, 1077.0),
 (549159213, 5740.0),
 (898316315, 20.0),
 (1017484769, 690.0),
 (733025646, 14546.0),
 (909624960, 1318.0),
 (1086459983, 3114.0),
 (593007494, 6269.0),
 (660179663, 3250.0),
 (1097157656, 3497.0),
 (751776863, 706.0),
 (1253973206, 2231.0),
 (828790972, 3408.0),
 (933413410, 3906.0),
 (550959163, 4844.0),
 (933926000, 3477.0),
 (953168456, 829.0),
 (1124754999, 19.0),
 (832949213, 1384.0),
 (801216472, 552.0),
 (929898500, 4909.0),
 (850490510, 12966.0),
 (1099394392, 569.0),
 (674885710, 5007.0),
 (1122991519, 2400.0),
 (904781800, 1217.0),
 (974438263, 122.0),
 (875608094, 1938.0),
 (1061890181, 220.0),
 (1033144189, 1477.0),
 (860406062, 4311.0),
 (692445545, 5302.0),
 (974775647, 1452.0),
 (1109819647, 317.0),
 (1223469038, 160.0),
 (511503677, 12149.0),
 (1190558632, 23.0),
 (641665398, 199.0),
 (964917582, 1356.0),
 (859922576, 9975.0),
 (817353671, 5286.0),
 (990559192, 1427.0),
 (713391965, 8915.0),
 (722565148, 17508.0),
 (532874347, 12606.0),
 (655464934, 5167.0),
 (919930954, 12312.0)]

In [22]:
 pd.read_excel("E:\DATA SCIENCE\data fsds_\Dress Sales.xlsx")

,Dress_ID,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,D14,D15,D16,D17,D18,D19,D20,D21,D22,D23
0,1006032852,2114,2274,2491,2660,2727,2887,2930,3119,3204,...,3554,3624.0,3706,3746.0,3795.0,3832.0,3897,3923.0,3985.0,4048
1,1212192089,151,275,570,750,813,1066,1164,1558,1756,...,2710,2942.0,3258,3354.0,3475.0,3654.0,3911,4024.0,4125.0,4277
2,1190380701,6,7,7,7,8,8,9,10,10,...,11,11.0,11,11.0,11.0,11.0,11,11.0,11.0,11
3,966005983,1005,1128,1326,1455,1507,1621,1637,1723,1746,...,1878,1892.0,1914,1924.0,1929.0,1941.0,1952,1955.0,1959.0,1963
4,876339541,996,1175,1304,1396,1432,1559,1570,1638,1655,...,2032,2156.0,2252,2312.0,2387.0,2459.0,2544,2614.0,2693.0,2736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,0,0,0,560,554,544,537,525,519,...,400,388.0,360,364.0,372.0,377.0,380,382.0,384.0,285
496,722565148,0,0,0,875,866,861,854,850,844,...,859,866.0,882,888.0,895.0,898.0,906,913.0,919.0,931
497,532874347,0,0,0,734,728,726,715,694,690,...,616,597.0,586,569.0,561.0,555.0,551,546.0,535.0,520
498,655464934,0,0,0,254,259,261,263,268,270,...,257,256.0,255,254.0,253.0,250.0,249,249.0,249.0,248
499,919930954,0,0,0,538,545,558,563,578,585,...,628,632.0,639,645.0,651.0,655.0,660,668.0,674.0,680

In [19]:
df2.to_json("jsonattributedataset.json")

In [24]:
pip install pymongo

Note: you may need to restart the kernel to use updated packages.Collecting pymongo

  Downloading pymongo-4.2.0-cp39-cp39-win_amd64.whl (374 kB)
Installing collected packages: pymongo
Successfully installed pymongo-4.2.0

In [25]:
pip install pymongo[srv]

Requirement already satisfied: pymongo[srv] in c:\users\hp\anaconda3\lib\site-packages (4.2.0)Note: you may need to restart the kernel to use updated packages.

Collecting dnspython<3.0.0,>=1.16.0
  Using cached dnspython-2.2.1-py3-none-any.whl (269 kB)
Installing collected packages: dnspython
Successfully installed dnspython-2.2.1

In [5]:
#restart the kernal after installing the packadges
import pymongo

client = pymongo.MongoClient("mongodb+srv://ankitdubey:ankitmongo04@cluster0.ctr9gra.mongodb.net/?retryWrites=true&w=majority")
db = client.test
database = ["DressDb"]
collection = database["Attribute"]
with open('jsonattributedataset.json') as file:
    file_data = json.load(file)
if isinstance(file_data, list):
    Collection.insert_many(file_data) 
else:
    Collection.insert_one(file_data)

TypeError: list indices must be integers or slices, not str

In [13]:
df5 = pd.read_json("C:\Users\HP\Jupyter codes\jsonattributedataset.json")
df5

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (1714133513.py, line 1)